# Generated by Django 5.2 on 2026-03-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JiraSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'JIRA Setting',
                'verbose_name_plural': 'JIRA Settings',
            },
        ),
    ]
